server:
  port: 8080
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://containers-us-west-192.railway.app:7701/doctorado_devengamiento
    username: postgres
    password: msCN0wjQOrJLWJLHrCxN
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: davidrokero666@gmail.com
    password: 0983837084davidscreamolexero
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
enviroments:
  linkFrontEnd: http://localhost:5173
  mailResponseFiniquito: nikomont123@gmail.com