server:
  port: 8080
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/railway
    username: postgres
    password: 277353
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
  mail:
    host: unknown
    port: 0
    username: unknown
    password: unknown
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: unknown
env:
  linkFront: http://localhost:8000/
  mailFrom: YSP_fashionStore@outlook.es
  mailToTest: pnbalseca@uce.edu.ec
