server:
  port: 8080
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://containers-us-west-155.railway.app:8020/railway
    username: postgres
    password: nxuAlU1rljppQrouxUpG
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    open-in-view: false
  data:
    mongodb:
      uri: mongodb://localhost:27017
      authentication-database: root
      database: railway
  mail:
    host: unknown
    port: 1
    username: unknown
    password: unknown
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: unknown
env:
  linkFront: http://localhost:8000/
  mailFrom: unknown
  inProduction: false
