server:
  port: 8080
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/railway
    username: postgres
    password: 277353
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
  mail:
    host: smtp.office365.com
    port: 587
    username: YSP_fashionStore@outlook.es
    password: Yps_2020
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
enviroments:
  linkFrontEnd: http://localhost:3000
  mailResponseFiniquito: nikomont123@gmail.com