server:
  port: 8080
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://containers-us-west-146.railway.app:6556/railway
    username: postgres
    password: mC2znCQjiou4AWQx3uz7
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
  mail:
    host: smtp.office365.com
    port: 587
    username: YSP_fashionStore@outlook.es
    password: Yps_2020
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
enviroments:
  linkFrontEnd: http://localhost:3000
  mailResponseFiniquito: nikomont123@gmail.com