server:
  port: 8080
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/railway
    username: postgres
    password: 277353
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
  mail:
    host: smtp.us-west-1.mailertogo.net
    port: 587
    username: 41ad632dda0fb13e3a44cc9c376320ef
    password: 181a2236effa842634511dd1f8b12604c14bd0daa682f2daa5c813a412425af0
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
enviroments:
  linkFrontEnd: http://localhost:3000
  mailResponseFiniquito: nikomont123@gmail.com