server:
  port: 8080
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/railway
    username: postgres
    password: 277353
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: 0d69cac26fb660
    password: 22b1951a2b72e6
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
env:
  linkFront: http://localhost:8000/
  mailFrom: pbalsecamh5b@outlook.com
